### ISSUE TITLE
Encoding 950 data could not be found on iOS

### ISSUE THREAD

**Issue by winsonet** [dinesh4official/XFPDF#3]
don't know why when I tried your sample and run on iOS, it shows below error:

```
Encoding 950 data could not be found. Make sure you have correct international codeset assembly installed and enabled.
```

**Comment by dinesh4official** [comment]
@winsonet , 

Thanks for the comment :)

To be honset, i can't able to reproduce this issue either through host from VS to MAC and deploy the application in MAC directly.

And, I don't have idea about `Encoding 950`. If it is about international codeset assembly. Refer the below link.

https://www.jocheojeda.com/2019/04/18/xamarin-xpo-system-notsupportedexception-encoding-1252-data-could-not-be-found-make-sure-you-have-correct-international-codeset-assembly-installed-and-enabled/

Hope it may resolve your issue!

**Comment by winsonet** [comment]
thanks for your reply, but it doesn't work for me :(

**Comment by dinesh4official** [comment]
@winsonet , 

I feel that this issue might not be related to the application and i can't able to replicate under my circumstance. So, please report Xamarin team.

https://github.com/xamarin/Xamarin.Forms/issues

I suggest you to try with other machine. I tried with all machines i have.

**Comment by winsonet** [comment]
ok, thanks!
